<?php if ( ! defined('BASEPATH')) exit('No direct script access allowed');

class Generate_tables extends CI_Controller {

  function __construct()
  {
    parent::__construct();

    $this->load->database('development');
  }

  /**
   *
   */
  public function index()
  {
    
  }

  /**
   *
   */
  private function speciality()
  {

    $speciality = array(

      array("code" => "1" , "name" => "Zahnarzt", ),
      array("code" => "2" , "name" => "Allgemeinarzt / Hausarzt", ),
      array("code" => "3" , "name" => "Frauenarzt / Gynäkologe", ),
      array("code" => "4" , "name" => "HNO-Arzt", ),
      array("code" => "5" , "name" => "Hautarzt / Dermatologe", ),
      array("code" => "6" , "name" => "Augenarzt", ),
      array("code" => "7" , "name" => "Orthopäde", ),
      array("code" => "8" , "name" => "Psychotherapeut", ),
      array("code" => "9" , "name" => "Urologe", ),

      array("code" => "10", "name" => "Plastische / Ästhetische Chirurgie", ),
      array("code" => "11", "name" => "Neurologe", ),
      array("code" => "12", "name" => "Kieferorthopäde", ),
      array("code" => "13", "name" => "Kinderzahnarzt", ),
      array("code" => "14", "name" => "Gefäßchirurg", ),
      array("code" => "15", "name" => "Mund-Kiefer-Gesichtschirurg", ),
      array("code" => "17", "name" => "Oralchirurg", ),
      array("code" => "18", "name" => "Radiologie", ),
      array("code" => "19", "name" => "Homöopath", ),
      
      array("code" => "20", "name" => "Internist", ),
      array("code" => "21", "name" => "Psychiater", ),
      array("code" => "22", "name" => "Allergologe", ),
      array("code" => "23", "name" => "Facharzt für Venenleiden", ),
      array("code" => "24", "name" => "Isopathe", ),
      array("code" => "25", "name" => "Anästhesist", ),
      array("code" => "26", "name" => "Heilpraktiker", ),
      array("code" => "27", "name" => "Traditionelle chinesische Medizin", ),
      array("code" => "28", "name" => "Akupunkteur", ),
      array("code" => "29", "name" => "Psychosomatiker", ),
      
      array("code" => "30", "name" => "Implantologe", ),
      array("code" => "31", "name" => "Pflanzenheilkunde", ),
      array("code" => "32", "name" => "Massage", ),
      array("code" => "33", "name" => "Physiotherapeut", ),
      array("code" => "34", "name" => "Kinderarzt", ),
      array("code" => "35", "name" => "Kardiologe", ),
      array("code" => "36", "name" => "Kinderwunsch / Reproduktionsmedizin", ),
      array("code" => "37", "name" => "Diabetologe", ),
      array("code" => "38", "name" => "Chirurg", ),
      array("code" => "39", "name" => "Refraktive Chirurgie / Augenoperationen", ),
      
      array("code" => "40", "name" => "ästhetische Medizin", ),
      array("code" => "41", "name" => "Ergotherapie", ),
      array("code" => "42", "name" => "Schmerztherapie", ),
      array("code" => "43", "name" => "Pneumologe / Lungenfacharzt", ),
      array("code" => "45", "name" => "Hausbesuch", ),
      array("code" => "46", "name" => "Neurochirurg", ),
      array("code" => "47", "name" => "Wirbelsäulenchirurg", ),
      array("code" => "48", "name" => "MRT-Diagnostik", ),
      
      array("code" => "60", "name" => "Nuklearmedizin", ),
      array("code" => "62", "name" => "Heilpraktiker für Psychotherapie", ),
      array("code" => "63", "name" => "Facharzt für rehabilitative und physikalische Medizin", ),
      array("code" => "64", "name" => "Gastroenterologe", ),
      array("code" => "65", "name" => "Hypnosetherapeut", ),
      array("code" => "66", "name" => "Bioresonanztherapie", ),
      array("code" => "67", "name" => "Naturheilkunde", ),
      array("code" => "68", "name" => "Andrologie", ),
      array("code" => "69", "name" => "Proktologie / Erkrankungen des Enddarms", ),
      
      array("code" => "70", "name" => "Endokrinologie", ),
      array("code" => "71", "name" => "Geriatrie / Altersheilkunde", ),
      array("code" => "73", "name" => "Rheumatologie", ),
      array("code" => "74", "name" => "Schlafmedizin", ),
      array("code" => "75", "name" => "Präventivmedizin", ),
      array("code" => "76", "name" => "Sportmedizin", ),
      array("code" => "77", "name" => "Osteologie", ),
      array("code" => "78", "name" => "Ernährungsmedizin", ),
      array("code" => "79", "name" => "Anthroposophische Medizin", ),
      
      array("code" => "80", "name" => "Komplementäre Onkologie", ),
      array("code" => "81", "name" => "Logopädie", ),
      array("code" => "82", "name" => "Psychologe", ),
      array("code" => "83", "name" => "Psychologischer Psychotherapeut", ),
      array("code" => "84", "name" => "Laserheilkunde", ),
      array("code" => "85", "name" => "Unfallchirurgie", ),
      array("code" => "86", "name" => "Orthopädie und Unfallchirurgie", ),
      array("code" => "87", "name" => "Durchgangsarzt", ),

    );

    foreach ($speciality as $row) {
      $this->db->set('code', $row['code']);
      $this->db->set('name', $row['name']);

      $this->db->insert('speciality');
    }

    echo "table speciality done.\n<br/>";
  
  }

  /**
   *
   */
  private function spec_treatment()
  {

    $speciality_treatment = array(
      array('speciality_code' => '1', 'code' => '1', 'name' => "Akute Zahnschmerzen", ), 
      array('speciality_code' => '1', 'code' => '24', 'name' => "Beratung: Implantat", ), 
      array('speciality_code' => '1', 'code' => '4', 'name' => "Beratung: Zahnersatz", ), 
      array('speciality_code' => '1', 'code' => '26', 'name' => "Bleaching/Zahnaufhellung ", ), 
      array('speciality_code' => '1', 'code' => '320', 'name' => "CEREC-Verfahren", ), 
      array('speciality_code' => '1', 'code' => '136', 'name' => "Ersttermin", ), 
      array('speciality_code' => '1', 'code' => '46', 'name' => "Funktionsdiagnostik/-therapie", ), 
      array('speciality_code' => '1', 'code' => '2', 'name' => "Füllungen", ), 
      array('speciality_code' => '1', 'code' => '142', 'name' => "Implantat", ), 
      array('speciality_code' => '1', 'code' => '240', 'name' => "Kiefergelenksbeschwerden", ), 
      array('speciality_code' => '1', 'code' => '143', 'name' => "Kindersprechstunde", ), 
      array('speciality_code' => '1', 'code' => '5', 'name' => "Kontrolluntersuchung", ), 
      array('speciality_code' => '1', 'code' => '45', 'name' => "Laserbehandlung", ), 
      array('speciality_code' => '1', 'code' => '165', 'name' => "Notfallsprechstunde", ), 
      array('speciality_code' => '1', 'code' => '47', 'name' => "Orale Chirurgie", ), 
      array('speciality_code' => '1', 'code' => '43', 'name' => "Parodontologie", ), 
      array('speciality_code' => '1', 'code' => '6', 'name' => "Professionelle Zahnreinigung", ), 
      array('speciality_code' => '1', 'code' => '41', 'name' => "Prophylaxe", ), 
      array('speciality_code' => '1', 'code' => '7', 'name' => "Sonstige Behandlung", ), 
      array('speciality_code' => '1', 'code' => '302', 'name' => "Sprechstunde", ), 
      array('speciality_code' => '1', 'code' => '25', 'name' => "Weisheitszahnproblematik", ), 
      array('speciality_code' => '1', 'code' => '3', 'name' => "Wurzelbehandlung/Endodontie", ), 
      array('speciality_code' => '1', 'code' => '42', 'name' => "Zahnschmuck", ), 
      array('speciality_code' => '1', 'code' => '44', 'name' => "Ästhetische Zahnheilkunde", ), 
      array('speciality_code' => '2', 'code' => '185', 'name' => "Check Up", ), 
      array('speciality_code' => '2', 'code' => '181', 'name' => "Chirotherapie", ), 
      array('speciality_code' => '2', 'code' => '186', 'name' => "EKG", ), 
      array('speciality_code' => '2', 'code' => '187', 'name' => "Ersttermin", ), 
      array('speciality_code' => '2', 'code' => '15', 'name' => "Sonstige Behandlung", ), 
      array('speciality_code' => '2', 'code' => '166', 'name' => "Sprechstunde", ), 
      array('speciality_code' => '3', 'code' => '68', 'name' => "3D Ultraschall", ), 
      array('speciality_code' => '3', 'code' => '8', 'name' => "Akute Beschwerden/Notfall", ), 
      array('speciality_code' => '3', 'code' => '80', 'name' => "Alternative Heilmethoden/ Akupunktur", ), 
      array('speciality_code' => '3', 'code' => '293', 'name' => "Ambulante Chemotherapie", ), 
      array('speciality_code' => '3', 'code' => '58', 'name' => "Ambulante Operationen", ), 
      array('speciality_code' => '3', 'code' => '307', 'name' => "Beckenbodenprobleme", ), 
      array('speciality_code' => '3', 'code' => '56', 'name' => "Beratung: Verhütung", ), 
      array('speciality_code' => '3', 'code' => '182', 'name' => "Empfängnisregelung Beratung", ), 
      array('speciality_code' => '3', 'code' => '137', 'name' => "Ersttermin", ), 
      array('speciality_code' => '3', 'code' => '59', 'name' => "Geschlechtskrankheiten", ), 
      array('speciality_code' => '3', 'code' => '9', 'name' => "Gespräch", ), 
      array('speciality_code' => '3', 'code' => '183', 'name' => "Halbjahreskontrolluntersuchung", ), 
      array('speciality_code' => '3', 'code' => '49', 'name' => "Hormonbehandlung", ), 
      array('speciality_code' => '3', 'code' => '140', 'name' => "Impfung", ), 
      array('speciality_code' => '3', 'code' => '48', 'name' => "Kinderwunsch", ), 
      array('speciality_code' => '3', 'code' => '10', 'name' => "Kontrolluntersuchung", ), 
      array('speciality_code' => '3', 'code' => '11', 'name' => "Krebsvorsorge ", ), 
      array('speciality_code' => '3', 'code' => '157', 'name' => "Nachsorge", ), 
      array('speciality_code' => '3', 'code' => '160', 'name' => "Notfallsprechstunde", ), 
      array('speciality_code' => '3', 'code' => '285', 'name' => "OP-Termin", ), 
      array('speciality_code' => '3', 'code' => '275', 'name' => "Polyzystisches Ovarialsyndrom", ), 
      array('speciality_code' => '3', 'code' => '57', 'name' => "Reisemedizin", ), 
      array('speciality_code' => '3', 'code' => '12', 'name' => "Schwangeren Erstuntersuchung ", ), 
      array('speciality_code' => '3', 'code' => '13', 'name' => "Schwangerschaftsvorsorge ", ), 
      array('speciality_code' => '3', 'code' => '14', 'name' => "Sonstige Behandlung", ), 
      array('speciality_code' => '3', 'code' => '168', 'name' => "Sprechstunde", ), 
      array('speciality_code' => '3', 'code' => '174', 'name' => "Teenager Sprechstunde", ), 
      array('speciality_code' => '3', 'code' => '175', 'name' => "Vorgespräche OP", ), 
      array('speciality_code' => '4', 'code' => '52', 'name' => "Allergiediagnostik", ), 
      array('speciality_code' => '4', 'code' => '94', 'name' => "Alternative Heilmethoden/ Akupunktur", ), 
      array('speciality_code' => '4', 'code' => '51', 'name' => "Ambulante Operationen", ), 
      array('speciality_code' => '4', 'code' => '53', 'name' => "Beratung: Hörgeräte", ), 
      array('speciality_code' => '4', 'code' => '131', 'name' => "Ersttermin", ), 
      array('speciality_code' => '4', 'code' => '84', 'name' => "Hördiagnostik/ Hörtest", ), 
      array('speciality_code' => '4', 'code' => '83', 'name' => "Hörgeräte: Versorgung und Kontrolle", ), 
      array('speciality_code' => '4', 'code' => '150', 'name' => "Kontrolle", ), 
      array('speciality_code' => '4', 'code' => '87', 'name' => "Krebsvorsorge", ), 
      array('speciality_code' => '4', 'code' => '162', 'name' => "Notfallsprechstunde", ), 
      array('speciality_code' => '4', 'code' => '55', 'name' => "Plastische Chirurgie", ), 
      array('speciality_code' => '4', 'code' => '54', 'name' => "Reisemedizin", ), 
      array('speciality_code' => '4', 'code' => '82', 'name' => "Riech- und Geschmackstörung", ), 
      array('speciality_code' => '4', 'code' => '85', 'name' => "Schnarchtherapie", ), 
      array('speciality_code' => '4', 'code' => '50', 'name' => "Schwindeltherapie/ Tinitus", ), 
      array('speciality_code' => '4', 'code' => '16', 'name' => "Sonstige Behandlung", ), 
      array('speciality_code' => '4', 'code' => '169', 'name' => "Sprechstunde", ), 
      array('speciality_code' => '4', 'code' => '81', 'name' => "Stimm- und Sprachstörung", ), 
      array('speciality_code' => '4', 'code' => '86', 'name' => "Tauchtauglichkeit", ), 
      array('speciality_code' => '5', 'code' => '65', 'name' => "Aknetherapie", ), 
      array('speciality_code' => '5', 'code' => '62', 'name' => "Allergiediagnostik", ), 
      array('speciality_code' => '5', 'code' => '120', 'name' => "Allergietest", ), 
      array('speciality_code' => '5', 'code' => '63', 'name' => "Ambulante Operationen", ), 
      array('speciality_code' => '5', 'code' => '78', 'name' => "Beratung: Haarausfall", ), 
      array('speciality_code' => '5', 'code' => '125', 'name' => "Ersttermin", ), 
      array('speciality_code' => '5', 'code' => '67', 'name' => "Haut- und Geschlechtskrankheiten", ), 
      array('speciality_code' => '5', 'code' => '145', 'name' => "Kontrolle", ), 
      array('speciality_code' => '5', 'code' => '64', 'name' => "Kosmetische Behandlung: Fruchtsäurepeeling", ), 
      array('speciality_code' => '5', 'code' => '61', 'name' => "Krebsvorsorge", ), 
      array('speciality_code' => '5', 'code' => '60', 'name' => "Laserbehandlung", ), 
      array('speciality_code' => '5', 'code' => '159', 'name' => "Notfallsprechstunde", ), 
      array('speciality_code' => '5', 'code' => '79', 'name' => "Photodynamische Therapier/ Lichttherapie", ), 
      array('speciality_code' => '5', 'code' => '66', 'name' => "Reisemedizin", ), 
      array('speciality_code' => '5', 'code' => '17', 'name' => "Sonstige Behandlung", ), 
      array('speciality_code' => '6', 'code' => '72', 'name' => "Ambulante Operationen", ), 
      array('speciality_code' => '6', 'code' => '73', 'name' => "Beratung: Diabetes mellitus", ), 
      array('speciality_code' => '6', 'code' => '70', 'name' => "Beratung: Kontaktlinsen", ), 
      array('speciality_code' => '6', 'code' => '126', 'name' => "Ersttermin", ), 
      array('speciality_code' => '6', 'code' => '76', 'name' => "Kontaktlinsen: Anpassung und Kontrolle", ), 
      array('speciality_code' => '6', 'code' => '146', 'name' => "Kontrolle", ), 
      array('speciality_code' => '6', 'code' => '75', 'name' => "Kosmetische Chirurgie", ), 
      array('speciality_code' => '6', 'code' => '69', 'name' => "Laserbehandlung", ), 
      array('speciality_code' => '6', 'code' => '74', 'name' => "Refraktive Chirurgie", ), 
      array('speciality_code' => '6', 'code' => '77', 'name' => "Reisemedizin", ), 
      array('speciality_code' => '6', 'code' => '71', 'name' => "Sehtest", ), 
      array('speciality_code' => '6', 'code' => '18', 'name' => "Sonstige Behandlung", ), 
      array('speciality_code' => '6', 'code' => '167', 'name' => "Sprechstunde", ), 
      array('speciality_code' => '7', 'code' => '101', 'name' => "Alternative Heilmethoden/ Akupunktur", ), 
      array('speciality_code' => '7', 'code' => '104', 'name' => "Ambulante Operationen", ), 
      array('speciality_code' => '7', 'code' => '133', 'name' => "Ersttermin", ), 
      array('speciality_code' => '7', 'code' => '99', 'name' => "Ostheoporose", ), 
      array('speciality_code' => '7', 'code' => '98', 'name' => "Schmerztherapie", ), 
      array('speciality_code' => '7', 'code' => '19', 'name' => "Sonstige Behandlung", ), 
      array('speciality_code' => '7', 'code' => '100', 'name' => "Sportmedizinische Untersuchung", ), 
      array('speciality_code' => '7', 'code' => '171', 'name' => "Sprechstunde", ), 
      array('speciality_code' => '7', 'code' => '102', 'name' => "Stoßwellentherapie", ), 
      array('speciality_code' => '7', 'code' => '103', 'name' => "Säuglings- und Kinderorthopädie", ), 
      array('speciality_code' => '7', 'code' => '294', 'name' => "Taping", ), 
      array('speciality_code' => '8', 'code' => '309', 'name' => "Burnout", ), 
      array('speciality_code' => '8', 'code' => '271', 'name' => "Ersttermin", ), 
      array('speciality_code' => '8', 'code' => '317', 'name' => "Gestalttherapie", ), 
      array('speciality_code' => '8', 'code' => '270', 'name' => "Kognitive Verhaltenstherapie", ), 
      array('speciality_code' => '8', 'code' => '318', 'name' => "Paartherapie", ), 
      array('speciality_code' => '9', 'code' => '109', 'name' => "Ambulante Operationen", ), 
      array('speciality_code' => '9', 'code' => '122', 'name' => "Blasenspiegelung (Frau)", ), 
      array('speciality_code' => '9', 'code' => '123', 'name' => "Blasenspiegelung (Mann)", ), 
      array('speciality_code' => '9', 'code' => '265', 'name' => "Circumcision", ), 
      array('speciality_code' => '9', 'code' => '105', 'name' => "Erektionsstörungen", ), 
      array('speciality_code' => '9', 'code' => '135', 'name' => "Ersttermin", ), 
      array('speciality_code' => '9', 'code' => '106', 'name' => "Fruchtbarkeitsuntersuchung/ -behandlung", ), 
      array('speciality_code' => '9', 'code' => '110', 'name' => "Geschlechtskrankheiten", ), 
      array('speciality_code' => '9', 'code' => '138', 'name' => "Harnröhrenabstrich", ), 
      array('speciality_code' => '9', 'code' => '113', 'name' => "Hämorrhoiden", ), 
      array('speciality_code' => '9', 'code' => '112', 'name' => "Kinderurologie", ), 
      array('speciality_code' => '9', 'code' => '308', 'name' => "Kontinenzprobleme", ), 
      array('speciality_code' => '9', 'code' => '155', 'name' => "Krebsvorsorge", ), 
      array('speciality_code' => '9', 'code' => '107', 'name' => "Medizinische Vorhautentfernung", ), 
      array('speciality_code' => '9', 'code' => '156', 'name' => "Metabolic Balance", ), 
      array('speciality_code' => '9', 'code' => '164', 'name' => "Notfallsprechstunde", ), 
      array('speciality_code' => '9', 'code' => '111', 'name' => "Prostatadiagnostik", ), 
      array('speciality_code' => '9', 'code' => '21', 'name' => "Sonstige Behandlung", ), 
      array('speciality_code' => '9', 'code' => '172', 'name' => "Sprechstunde", ), 
      array('speciality_code' => '9', 'code' => '264', 'name' => "Vasektomie", ), 
      array('speciality_code' => '9', 'code' => '176', 'name' => "Vorsorge", ), 
      array('speciality_code' => '9', 'code' => '108', 'name' => "Vorsorgeuntersuchung Mann", ), 
      array('speciality_code' => '10', 'code' => '199', 'name' => "Armstraffung", ), 
      array('speciality_code' => '10', 'code' => '200', 'name' => "Augenlidstraffung", ), 
      array('speciality_code' => '10', 'code' => '201', 'name' => "Bauchdeckenstraffung", ), 
      array('speciality_code' => '10', 'code' => '202', 'name' => "Bodylifting", ), 
      array('speciality_code' => '10', 'code' => '203', 'name' => "Botulinumtoxin", ), 
      array('speciality_code' => '10', 'code' => '205', 'name' => "Brustreduktion beim Mann", ), 
      array('speciality_code' => '10', 'code' => '89', 'name' => "Brustvergrößerung/ -verkleinerung", ), 
      array('speciality_code' => '10', 'code' => '206', 'name' => "Faltenunterspritzung", ), 
      array('speciality_code' => '10', 'code' => '93', 'name' => "Gesichtslifting/ facelifting", ), 
      array('speciality_code' => '10', 'code' => '207', 'name' => "Haartransplantation", ), 
      array('speciality_code' => '10', 'code' => '88', 'name' => "Handchirurgie", ), 
      array('speciality_code' => '10', 'code' => '208', 'name' => "Implantat- wechsel", ), 
      array('speciality_code' => '10', 'code' => '209', 'name' => "Kinnkorrektur", ), 
      array('speciality_code' => '10', 'code' => '90', 'name' => "Liposuktion/ Fettabsaugen", ), 
      array('speciality_code' => '10', 'code' => '210', 'name' => "Lippenvergrösserung", ), 
      array('speciality_code' => '10', 'code' => '91', 'name' => "Narbenentfernung", ), 
      array('speciality_code' => '10', 'code' => '211', 'name' => "Nasenkorrektur", ), 
      array('speciality_code' => '10', 'code' => '212', 'name' => "Ohrenkorrektur", ), 
      array('speciality_code' => '10', 'code' => '233', 'name' => "Penisverlängerung", ), 
      array('speciality_code' => '10', 'code' => '95', 'name' => "Permanent Make-Up", ), 
      array('speciality_code' => '10', 'code' => '97', 'name' => "Phlebologie", ), 
      array('speciality_code' => '10', 'code' => '213', 'name' => "Profilkorrektur", ), 
      array('speciality_code' => '10', 'code' => '214', 'name' => "Schamlippenverkleinerung", ), 
      array('speciality_code' => '10', 'code' => '92', 'name' => "Schweißdrüsenentfernung", ), 
      array('speciality_code' => '10', 'code' => '22', 'name' => "Sonstige Behandlung", ), 
      array('speciality_code' => '10', 'code' => '215', 'name' => "Stirnlifting / Brauenlifting", ), 
      array('speciality_code' => '10', 'code' => '96', 'name' => "Unfallchirurgie", ), 
      array('speciality_code' => '11', 'code' => '23', 'name' => "Sonstige Behandlung", ), 
      array('speciality_code' => '12', 'code' => '20', 'name' => "Sonstige Behandlung", ), 
      array('speciality_code' => '13', 'code' => '239', 'name' => "Ersttermin", ), 
      array('speciality_code' => '13', 'code' => '304', 'name' => "Kontrolluntersuchung", ), 
      array('speciality_code' => '13', 'code' => '303', 'name' => "Schmerzfall", ), 
      array('speciality_code' => '13', 'code' => '301', 'name' => "Sprechstunde", ), 
      array('speciality_code' => '14', 'code' => '128', 'name' => "Ersttermin", ), 
      array('speciality_code' => '14', 'code' => '147', 'name' => "Kontrolle", ), 
      array('speciality_code' => '15', 'code' => '178', 'name' => "Sprechstunde", ), 
      array('speciality_code' => '17', 'code' => '238', 'name' => "Orale Chirurgie", ), 
      array('speciality_code' => '18', 'code' => '221', 'name' => "CT", ), 
      array('speciality_code' => '18', 'code' => '224', 'name' => "Duplex-Sonographie", ), 
      array('speciality_code' => '18', 'code' => '114', 'name' => "Kinderradiologie", ), 
      array('speciality_code' => '18', 'code' => '227', 'name' => "Mammographie", ), 
      array('speciality_code' => '18', 'code' => '234', 'name' => "MRT-Diagnostik", ), 
      array('speciality_code' => '18', 'code' => '226', 'name' => "Röntgen", ), 
      array('speciality_code' => '18', 'code' => '115', 'name' => "Sonstige Behandlungen", ), 
      array('speciality_code' => '18', 'code' => '223', 'name' => "Ultraschall-Sonographie", ), 
      array('speciality_code' => '19', 'code' => '261', 'name' => "Homöopathische Therapie", ), 
      array('speciality_code' => '20', 'code' => '124', 'name' => "Check Up", ), 
      array('speciality_code' => '20', 'code' => '177', 'name' => "EKG", ), 
      array('speciality_code' => '20', 'code' => '306', 'name' => "Ergometrie", ), 
      array('speciality_code' => '20', 'code' => '132', 'name' => "Ersttermin", ), 
      array('speciality_code' => '20', 'code' => '139', 'name' => "Impfung", ), 
      array('speciality_code' => '20', 'code' => '151', 'name' => "Kontrolle", ), 
      array('speciality_code' => '20', 'code' => '163', 'name' => "Notfallsprechstunde", ), 
      array('speciality_code' => '20', 'code' => '170', 'name' => "Sprechstunde", ), 
      array('speciality_code' => '20', 'code' => '305', 'name' => "Tauchtauglichkeit", ), 
      array('speciality_code' => '21', 'code' => '217', 'name' => "Ersttermin", ), 
      array('speciality_code' => '22', 'code' => '119', 'name' => "Allergietest", ), 
      array('speciality_code' => '22', 'code' => '218', 'name' => "Bioresonanz", ), 
      array('speciality_code' => '22', 'code' => '121', 'name' => "Ersttermin", ), 
      array('speciality_code' => '22', 'code' => '144', 'name' => "Kontrolle", ), 
      array('speciality_code' => '22', 'code' => '153', 'name' => "Krebsvorsorge", ), 
      array('speciality_code' => '22', 'code' => '158', 'name' => "Notfallsprechstunde", ), 
      array('speciality_code' => '23', 'code' => '129', 'name' => "Ersttermin", ), 
      array('speciality_code' => '23', 'code' => '148', 'name' => "Kontrolle", ), 
      array('speciality_code' => '23', 'code' => '154', 'name' => "Krebsvorsorge", ), 
      array('speciality_code' => '23', 'code' => '161', 'name' => "Notfallsprechstunde", ), 
      array('speciality_code' => '24', 'code' => '251', 'name' => "Biokybernetische Medizin", ), 
      array('speciality_code' => '25', 'code' => '252', 'name' => "Anästhesist", ), 
      array('speciality_code' => '26', 'code' => '33', 'name' => "Allergien", ), 
      array('speciality_code' => '26', 'code' => '34', 'name' => "Autoimmunerkrankungen", ), 
      array('speciality_code' => '26', 'code' => '118', 'name' => "Beratung", ), 
      array('speciality_code' => '26', 'code' => '27', 'name' => "Beschwerden des Bewegungsapparats", ), 
      array('speciality_code' => '26', 'code' => '36', 'name' => "Diabetes", ), 
      array('speciality_code' => '26', 'code' => '28', 'name' => "Entgiftung und Ausleitungstherapie", ), 
      array('speciality_code' => '26', 'code' => '290', 'name' => "Ersttermin", ), 
      array('speciality_code' => '26', 'code' => '130', 'name' => "Ersttermin", ), 
      array('speciality_code' => '26', 'code' => '39', 'name' => "Gewichtsreduktion", ), 
      array('speciality_code' => '26', 'code' => '149', 'name' => "Kontrolle", ), 
      array('speciality_code' => '26', 'code' => '37', 'name' => "Kopfschmerzen und Migräne", ), 
      array('speciality_code' => '26', 'code' => '38', 'name' => "Menstruations- und Wechseljahrsbeschwerden", ), 
      array('speciality_code' => '26', 'code' => '32', 'name' => "Nahrungsmittelunverträglichkeiten", ), 
      array('speciality_code' => '26', 'code' => '35', 'name' => "Neurodermitis", ), 
      array('speciality_code' => '26', 'code' => '29', 'name' => "Schmerzsyndrome", ), 
      array('speciality_code' => '26', 'code' => '31', 'name' => "Stoffwechselerkrankungen", ), 
      array('speciality_code' => '26', 'code' => '30', 'name' => "Verdauungsstörungen", ), 
      array('speciality_code' => '32', 'code' => '310', 'name' => "Massagetherapie", ), 
      array('speciality_code' => '27', 'code' => '241', 'name' => "chinesische Kräutertherapie", ), 
      array('speciality_code' => '27', 'code' => '289', 'name' => "Ersttermin", ), 
      array('speciality_code' => '27', 'code' => '242', 'name' => "Traditionelle Chinesische Medizin", ), 
      array('speciality_code' => '28', 'code' => '237', 'name' => "Akupunktur", ), 
      array('speciality_code' => '29', 'code' => '311', 'name' => "Ersttermin", ), 
      array('speciality_code' => '30', 'code' => '180', 'name' => "Chirurgie", ), 
      array('speciality_code' => '30', 'code' => '141', 'name' => "Implantat", ), 
      array('speciality_code' => '30', 'code' => '179', 'name' => "Laserbehandlung", ), 
      array('speciality_code' => '30', 'code' => '173', 'name' => "Sprechstunde", ), 
      array('speciality_code' => '31', 'code' => '313', 'name' => "Ayurveda", ), 
      array('speciality_code' => '31', 'code' => '312', 'name' => "Traditionelle Chinesische Medizin", ), 
      array('speciality_code' => '31', 'code' => '314', 'name' => "traditionelle Phythotherapie", ), 
      array('speciality_code' => '33', 'code' => '191', 'name' => "Krankengymnastik", ), 
      array('speciality_code' => '33', 'code' => '195', 'name' => "Lymphdrainagen", ), 
      array('speciality_code' => '33', 'code' => '192', 'name' => "Manuelle Therapie", ), 
      array('speciality_code' => '33', 'code' => '196', 'name' => "Massagen", ), 
      array('speciality_code' => '33', 'code' => '193', 'name' => "Osteopathie", ), 
      array('speciality_code' => '33', 'code' => '197', 'name' => "Physikalische Therapie", ), 
      array('speciality_code' => '33', 'code' => '194', 'name' => "Sportphysiotherapie", ), 
      array('speciality_code' => '34', 'code' => '184', 'name' => "kindersprechstunde", ), 
      array('speciality_code' => '35', 'code' => '236', 'name' => "Sprechstunde", ), 
      array('speciality_code' => '36', 'code' => '188', 'name' => "Kinderwunsch", ), 
      array('speciality_code' => '37', 'code' => '272', 'name' => "Diabetes mellitus", ), 
      array('speciality_code' => '37', 'code' => '127', 'name' => "Ersttermin", ), 
      array('speciality_code' => '38', 'code' => '340', 'name' => "ACP/PRP-Behandlungen", ), 
      array('speciality_code' => '38', 'code' => '338', 'name' => "Ambulante Operationen", ), 
      array('speciality_code' => '38', 'code' => '345', 'name' => "arthroskopische Gelenkchirurgie", ), 
      array('speciality_code' => '38', 'code' => '342', 'name' => "Endoprothetik (Hüft- und Kniegelenke)", ), 
      array('speciality_code' => '38', 'code' => '330', 'name' => "Ersttermin", ), 
      array('speciality_code' => '38', 'code' => '198', 'name' => "Ersttermin", ), 
      array('speciality_code' => '38', 'code' => '339', 'name' => "Extrakorporale Stoßwellentherapie", ), 
      array('speciality_code' => '38', 'code' => '332', 'name' => "Fußchirurgie", ), 
      array('speciality_code' => '38', 'code' => '334', 'name' => "Handchirurgie", ), 
      array('speciality_code' => '38', 'code' => '333', 'name' => "Hernienchirurgie", ), 
      array('speciality_code' => '38', 'code' => '341', 'name' => "Hyaloronsäurebehandlung (Arthrosebehandlung)", ), 
      array('speciality_code' => '38', 'code' => '336', 'name' => "Kassenärztliche chirurgische / unfallchirurgische Sprechstunde", ), 
      array('speciality_code' => '38', 'code' => '337', 'name' => "Kassenärztliche chirurgische / unfallchirurgische Sprechstunde", ), 
      array('speciality_code' => '38', 'code' => '335', 'name' => "Kniechirurgie", ), 
      array('speciality_code' => '38', 'code' => '344', 'name' => "Proktologie", ), 
      array('speciality_code' => '38', 'code' => '346', 'name' => "Sonographische Diagnostik", ), 
      array('speciality_code' => '38', 'code' => '343', 'name' => "Stationäre Operationen", ), 
      array('speciality_code' => '39', 'code' => '288', 'name' => "Ersttermin", ), 
      array('speciality_code' => '40', 'code' => '229', 'name' => "Botox", ), 
      array('speciality_code' => '40', 'code' => '228', 'name' => "Faltenunterspritzung", ), 
      array('speciality_code' => '40', 'code' => '230', 'name' => "G-Punkt-Unterspritzung", ), 
      array('speciality_code' => '40', 'code' => '284', 'name' => "Hyaluronsäure", ), 
      array('speciality_code' => '40', 'code' => '283', 'name' => "Laserbehandlung", ), 
      array('speciality_code' => '41', 'code' => '235', 'name' => "Ergotherapie", ), 
      array('speciality_code' => '42', 'code' => '253', 'name' => "Schmerztherapie", ), 
      array('speciality_code' => '43', 'code' => '266', 'name' => "Ersttermin", ), 
      array('speciality_code' => '45', 'code' => '189', 'name' => "Sonstige Behandlung", ), 
      array('speciality_code' => '46', 'code' => '190', 'name' => "Ersttermin", ), 
      array('speciality_code' => '47', 'code' => '216', 'name' => "Ersttermin", ), 
      array('speciality_code' => '48', 'code' => '282', 'name' => "Ellenbogen-MRT", ), 
      array('speciality_code' => '48', 'code' => '220', 'name' => "Gynäkologisches MRT", ), 
      array('speciality_code' => '48', 'code' => '278', 'name' => "Knie-MRT", ), 
      array('speciality_code' => '48', 'code' => '281', 'name' => "MRT der Hände", ), 
      array('speciality_code' => '48', 'code' => '279', 'name' => "MRT der Hüfte", ), 
      array('speciality_code' => '48', 'code' => '219', 'name' => "Neuro-MRT", ), 
      array('speciality_code' => '48', 'code' => '280', 'name' => "Schulter-MRT", ), 
      array('speciality_code' => '48', 'code' => '276', 'name' => "Schädel-MRT", ), 
      array('speciality_code' => '48', 'code' => '277', 'name' => "Wirbelsäulen-MRT", ), 
      array('speciality_code' => '60', 'code' => '324', 'name' => "Ersttermin", ), 
      array('speciality_code' => '62', 'code' => '247', 'name' => "Atemtherapie", ), 
      array('speciality_code' => '62', 'code' => '248', 'name' => "Gesprächstherapie", ), 
      array('speciality_code' => '62', 'code' => '245', 'name' => "Hypnose", ), 
      array('speciality_code' => '62', 'code' => '249', 'name' => "NLP (Neurolinguistisches Programmieren)", ), 
      array('speciality_code' => '62', 'code' => '243', 'name' => "Psychotherapie", ), 
      array('speciality_code' => '62', 'code' => '244', 'name' => "Singtherapie", ), 
      array('speciality_code' => '62', 'code' => '246', 'name' => "Stimmtherapie", ), 
      array('speciality_code' => '63', 'code' => '250', 'name' => "Sprechstunde", ), 
      array('speciality_code' => '64', 'code' => '257', 'name' => "Darmspiegelung", ), 
      array('speciality_code' => '64', 'code' => '254', 'name' => "Ersttermine", ), 
      array('speciality_code' => '64', 'code' => '256', 'name' => "Magenballon", ), 
      array('speciality_code' => '64', 'code' => '255', 'name' => "Magenspiegelung", ), 
      array('speciality_code' => '65', 'code' => '258', 'name' => "Hypnose", ), 
      array('speciality_code' => '65', 'code' => '259', 'name' => "Raucherentwöhnung", ), 
      array('speciality_code' => '66', 'code' => '260', 'name' => "Bioresonanztherapie", ), 
      array('speciality_code' => '67', 'code' => '295', 'name' => "Akupunktur", ), 
      array('speciality_code' => '67', 'code' => '300', 'name' => "Allergien", ), 
      array('speciality_code' => '67', 'code' => '299', 'name' => "Dorn- / Breußtherapie", ), 
      array('speciality_code' => '67', 'code' => '296', 'name' => "Fußreflexzonenmassage", ), 
      array('speciality_code' => '67', 'code' => '297', 'name' => "Irisdiagnose", ), 
      array('speciality_code' => '67', 'code' => '263', 'name' => "Schmerztherapie", ), 
      array('speciality_code' => '67', 'code' => '298', 'name' => "Triggerpunktmassage", ), 
      array('speciality_code' => '67', 'code' => '262', 'name' => "Tumortherapie", ), 
      array('speciality_code' => '69', 'code' => '267', 'name' => "Ersttermin", ), 
      array('speciality_code' => '70', 'code' => '268', 'name' => "Ersttermin", ), 
      array('speciality_code' => '71', 'code' => '269', 'name' => "First appointment", ), 
      array('speciality_code' => '73', 'code' => '274', 'name' => "Arthrose", ), 
      array('speciality_code' => '73', 'code' => '273', 'name' => "Osteoporose", ), 
      array('speciality_code' => '74', 'code' => '322', 'name' => "Ersttermin", ), 
      array('speciality_code' => '76', 'code' => '326', 'name' => "Sportmedizinische Beratung", ), 
      array('speciality_code' => '77', 'code' => '287', 'name' => "Ersttermin", ), 
      array('speciality_code' => '78', 'code' => '286', 'name' => "Ersttermin", ), 
      array('speciality_code' => '79', 'code' => '291', 'name' => "Ersttermin", ), 
      array('speciality_code' => '80', 'code' => '292', 'name' => "Ersttermin", ), 
      array('speciality_code' => '81', 'code' => '316', 'name' => "Ersttermin", ), 
      array('speciality_code' => '82', 'code' => '319', 'name' => "Ersttermin", ), 
      array('speciality_code' => '83', 'code' => '321', 'name' => "Ersttermin", ), 
      array('speciality_code' => '84', 'code' => '323', 'name' => "Ersttermine", ), 
      array('speciality_code' => '85', 'code' => '331', 'name' => "Ersttermin", ), 
      array('speciality_code' => '87', 'code' => '325', 'name' => "Arbeits-/Kita-, Schul- und Wegeunfälle", ), 
    );

    foreach ($speciality_treatment as $row) {
      $this->db->set('speciality_code', $row['speciality_code']);
      $this->db->set('code', $row['code']);
      $this->db->set('name', $row['name']);

      $this->db->insert('speciality_treatment');
    }

    echo "table speciality_treatment done.\n<br/>";
  
  }

  /**
   *
   */
  private function languages()
  {
    $langs = array(
      array( 'code' => 'ab', 'name' => 'Abkhaz', 'native' => 'аҧсуа бызшәа, аҧсшәа', ), 
      array( 'code' => 'aa', 'name' => 'Afar', 'native' => 'Afaraf', ), 
      array( 'code' => 'af', 'name' => 'Afrikaans', 'native' => 'Afrikaans', ), 
      array( 'code' => 'ak', 'name' => 'Akan', 'native' => 'Akan', ), 
      array( 'code' => 'sq', 'name' => 'Albanian', 'native' => 'Shqip', ), 
      array( 'code' => 'am', 'name' => 'Amharic', 'native' => 'አማርኛ', ), 
      array( 'code' => 'ar', 'name' => 'Arabic', 'native' => 'العربية', ), 
      array( 'code' => 'an', 'name' => 'Aragonese', 'native' => 'aragonés', ), 
      array( 'code' => 'hy', 'name' => 'Armenian', 'native' => 'Հայերեն', ), 
      array( 'code' => 'as', 'name' => 'Assamese', 'native' => 'অসমীয়া', ), 
      array( 'code' => 'av', 'name' => 'Avaric', 'native' => 'авар мацӀ, магӀарул мацӀ', ), 
      array( 'code' => 'ae', 'name' => 'Avestan', 'native' => 'avesta', ), 
      array( 'code' => 'ay', 'name' => 'Aymara', 'native' => 'aymar aru', ), 
      array( 'code' => 'az', 'name' => 'Azerbaijani', 'native' => 'azərbaycan dili', ), 
      array( 'code' => 'bm', 'name' => 'Bambara', 'native' => 'bamanankan', ), 
      array( 'code' => 'ba', 'name' => 'Bashkir', 'native' => 'башҡорт теле', ), 
      array( 'code' => 'eu', 'name' => 'Basque', 'native' => 'euskara, euskera', ), 
      array( 'code' => 'be', 'name' => 'Belarusian', 'native' => 'беларуская мова', ), 
      array( 'code' => 'bn', 'name' => 'Bengali, Ba', 'native' => 'বাংলা', ), 
      array( 'code' => 'bh', 'name' => 'Bihari', 'native' => 'भोजपुरी', ), 
      array( 'code' => 'bi', 'name' => 'Bislama', 'native' => 'Bislama', ), 
      array( 'code' => 'bs', 'name' => 'Bosnian', 'native' => 'bosanski jezik', ), 
      array( 'code' => 'br', 'name' => 'Breton', 'native' => 'brezhoneg', ), 
      array( 'code' => 'bg', 'name' => 'Bulgarian', 'native' => 'български език', ), 
      array( 'code' => 'my', 'name' => 'Burmese', 'native' => 'ဗမာစာ', ), 
      array( 'code' => 'ca', 'name' => 'Catalan, Valencian', 'native' => 'català, valencià', ), 
      array( 'code' => 'ch', 'name' => 'Chamorro', 'native' => 'Chamoru', ), 
      array( 'code' => 'ce', 'name' => 'Chechen', 'native' => 'нохчийн мотт', ), 
      array( 'code' => 'ny', 'name' => 'Chichewa, Chewa, Ny', 'native' => 'chiCheŵa, chinyanja', ), 
      array( 'code' => 'zh', 'name' => 'Chinese', 'native' => '中文 (Zhōngwén), 汉语, 漢語', ), 
      array( 'code' => 'cv', 'name' => 'Chuvash', 'native' => 'чӑваш чӗлхи', ), 
      array( 'code' => 'kw', 'name' => 'Cornish', 'native' => 'Kernewek', ), 
      array( 'code' => 'co', 'name' => 'Corsican', 'native' => 'corsu, lingua corsa', ), 
      array( 'code' => 'cr', 'name' => 'Cree', 'native' => 'ᓀᐦᐃᔭᐍᐏᐣ', ), 
      array( 'code' => 'hr', 'name' => 'Croatian', 'native' => 'hrvatski jezik', ), 
      array( 'code' => 'cs', 'name' => 'Czech', 'native' => 'čeština, český jazyk', ), 
      array( 'code' => 'da', 'name' => 'Danish', 'native' => 'dansk', ), 
      array( 'code' => 'dv', 'name' => 'Divehi, Dhivehi, Maldi', 'native' => 'ދިވެހި', ), 
      array( 'code' => 'nl', 'name' => 'Dutch', 'native' => 'Nederlands, Vlaams', ), 
      array( 'code' => 'dz', 'name' => 'Dzongkha', 'native' => 'རྫོང་ཁ', ), 
      array( 'code' => 'en', 'name' => 'English', 'native' => 'English', ), 
      array( 'code' => 'eo', 'name' => 'Esperanto', 'native' => 'Esperanto', ), 
      array( 'code' => 'et', 'name' => 'Estonian', 'native' => 'eesti, eesti keel', ), 
      array( 'code' => 'ee', 'name' => 'Ewe', 'native' => 'Eʋegbe', ), 
      array( 'code' => 'fo', 'name' => 'Faroese', 'native' => 'føroyskt', ), 
      array( 'code' => 'fj', 'name' => 'Fijian', 'native' => 'vosa Vakaviti', ), 
      array( 'code' => 'fi', 'name' => 'Finnish', 'native' => 'suomi, suomen kieli', ), 
      array( 'code' => 'fr', 'name' => 'French', 'native' => 'français, langue française', ), 
      array( 'code' => 'ff', 'name' => 'Fula, Fulah, Pulaar, P', 'native' => 'Fulfulde, Pulaar, Pular', ), 
      array( 'code' => 'gl', 'name' => 'Galician', 'native' => 'galego', ), 
      array( 'code' => 'ka', 'name' => 'Georgian', 'native' => 'ქართული', ), 
      array( 'code' => 'de', 'name' => 'German', 'native' => 'Deutsch', ), 
      array( 'code' => 'el', 'name' => 'Greek (mod', 'native' => 'ελληνικά', ), 
      array( 'code' => 'gn', 'name' => 'Guaraní', 'native' => 'Avañe\'ẽ', ), 
      array( 'code' => 'gu', 'name' => 'Gujarati', 'native' => 'ગુજરાતી', ), 
      array( 'code' => 'ht', 'name' => 'Haitian, Haitian Cr', 'native' => 'Kreyòl ayisyen', ), 
      array( 'code' => 'ha', 'name' => 'Hausa', 'native' => '(Hausa) هَوُسَ', ), 
      array( 'code' => 'he', 'name' => 'Hebrew (mod', 'native' => 'עברית', ), 
      array( 'code' => 'hz', 'name' => 'Herero', 'native' => 'Otjiherero', ), 
      array( 'code' => 'hi', 'name' => 'Hindi', 'native' => 'हिन्दी, हिंदी', ), 
      array( 'code' => 'ho', 'name' => 'Hiri Motu', 'native' => 'Hiri Motu', ), 
      array( 'code' => 'hu', 'name' => 'Hungarian', 'native' => 'magyar', ), 
      array( 'code' => 'ia', 'name' => 'Interlingua', 'native' => 'Interlingua', ), 
      array( 'code' => 'id', 'name' => 'Indonesian', 'native' => 'Bahasa Indonesia', ), 
      array( 'code' => 'ie', 'name' => 'Interlingue', 'native' => 'Originally called Occidental; then Interlingue after WWII', ), 
      array( 'code' => 'ga', 'name' => 'Irish', 'native' => 'Gaeilge', ), 
      array( 'code' => 'ig', 'name' => 'Igbo', 'native' => 'Asụsụ Igbo', ), 
      array( 'code' => 'ik', 'name' => 'Inupiaq', 'native' => 'Iñupiaq, Iñupiatun', ), 
      array( 'code' => 'io', 'name' => 'Ido', 'native' => 'Ido', ), 
      array( 'code' => 'is', 'name' => 'Icelandic', 'native' => 'Íslenska', ), 
      array( 'code' => 'it', 'name' => 'Italian', 'native' => 'italiano', ), 
      array( 'code' => 'iu', 'name' => 'Inuktitut', 'native' => 'ᐃᓄᒃᑎᑐᑦ', ), 
      array( 'code' => 'ja', 'name' => 'Japanese', 'native' => '日本語 (にほんご)', ), 
      array( 'code' => 'jv', 'name' => 'Javanese', 'native' => 'basa Jawa', ), 
      array( 'code' => 'kl', 'name' => 'Kalaallisut, Greenla', 'native' => 'kalaallisut, kalaallit oqaasii', ), 
      array( 'code' => 'kn', 'name' => 'Kannada', 'native' => 'ಕನ್ನಡ', ), 
      array( 'code' => 'kr', 'name' => 'Kanuri', 'native' => 'Kanuri', ), 
      array( 'code' => 'ks', 'name' => 'Kashmiri', 'native' => 'कश्मीरी, كشميري‎', ), 
      array( 'code' => 'kk', 'name' => 'Kazakh', 'native' => 'қазақ тілі', ), 
      array( 'code' => 'km', 'name' => 'Khmer', 'native' => 'ខ្មែរ, ខេមរភាសា, ភាសាខ្មែរ', ), 
      array( 'code' => 'ki', 'name' => 'Kikuyu, Gi', 'native' => 'Gĩkũyũ', ), 
      array( 'code' => 'rw', 'name' => 'Kinyarwanda', 'native' => 'Ikinyarwanda', ), 
      array( 'code' => 'ky', 'name' => 'Kyrgyz', 'native' => 'Кыргызча, Кыргыз тили', ), 
      array( 'code' => 'kv', 'name' => 'Komi', 'native' => 'коми кыв', ), 
      array( 'code' => 'kg', 'name' => 'Kongo', 'native' => 'Kikongo', ), 
      array( 'code' => 'ko', 'name' => 'Korean', 'native' => '한국어, 조선어', ), 
      array( 'code' => 'ku', 'name' => 'Kurdish', 'native' => 'Kurdî, كوردی‎', ), 
      array( 'code' => 'kj', 'name' => 'Kwanyama, Kuan', 'native' => 'Kuanyama', ), 
      array( 'code' => 'la', 'name' => 'Latin', 'native' => 'latine, lingua latina', ), 
      array( 'code' => 'lb', 'name' => 'Luxembourgish, Letzeburg', 'native' => 'Lëtzebuergesch', ), 
      array( 'code' => 'lg', 'name' => 'Ganda', 'native' => 'Luganda', ), 
      array( 'code' => 'li', 'name' => 'Limburgish, Limburgan, Limbu', 'native' => 'Limburgs', ), 
      array( 'code' => 'ln', 'name' => 'Lingala', 'native' => 'Lingála', ), 
      array( 'code' => 'lo', 'name' => 'Lao', 'native' => 'ພາສາລາວ', ), 
      array( 'code' => 'lt', 'name' => 'Lithuanian', 'native' => 'lietuvių kalba', ), 
      array( 'code' => 'lu', 'name' => 'Luba-Katanga', 'native' => 'Tshiluba', ), 
      array( 'code' => 'lv', 'name' => 'Latvian', 'native' => 'latviešu valoda', ), 
      array( 'code' => 'gv', 'name' => 'Manx', 'native' => 'Gaelg, Gailck', ), 
      array( 'code' => 'mk', 'name' => 'Macedonian', 'native' => 'македонски јазик', ), 
      array( 'code' => 'mg', 'name' => 'Malagasy', 'native' => 'fiteny malagasy', ), 
      array( 'code' => 'ms', 'name' => 'Malay', 'native' => 'bahasa Melayu, بهاس ملايو‎', ), 
      array( 'code' => 'ml', 'name' => 'Malayalam', 'native' => 'മലയാളം', ), 
      array( 'code' => 'mt', 'name' => 'Maltese', 'native' => 'Malti', ), 
      array( 'code' => 'mi', 'name' => 'Māori', 'native' => 'te reo Māori', ), 
      array( 'code' => 'mr', 'name' => 'Marathi (Marāṭhī)', 'native' => 'मराठी', ), 
      array( 'code' => 'mh', 'name' => 'Marshallese', 'native' => 'Kajin M̧ajeļ', ), 
      array( 'code' => 'mn', 'name' => 'Mongolian', 'native' => 'монгол', ), 
      array( 'code' => 'na', 'name' => 'Nauru', 'native' => 'Ekakairũ Naoero', ), 
      array( 'code' => 'nv', 'name' => 'Navajo, Na', 'native' => 'Diné bizaad, Dinékʼehǰí', ), 
      array( 'code' => 'nd', 'name' => 'Northern Ndebele', 'native' => 'isiNdebele', ), 
      array( 'code' => 'ne', 'name' => 'Nepali', 'native' => 'नेपाली', ), 
      array( 'code' => 'ng', 'name' => 'Ndonga', 'native' => 'Owambo', ), 
      array( 'code' => 'nb', 'name' => 'Norwegian Bokmål', 'native' => 'Norsk bokmål', ), 
      array( 'code' => 'nn', 'name' => 'Norwegian Nynorsk', 'native' => 'Norsk nynorsk', ), 
      array( 'code' => 'no', 'name' => 'Norwegian', 'native' => 'Norsk', ), 
      array( 'code' => 'ii', 'name' => 'Nuosu', 'native' => 'ꆈꌠ꒿ Nuosuhxop', ), 
      array( 'code' => 'nr', 'name' => 'Southern Ndebele', 'native' => 'isiNdebele', ), 
      array( 'code' => 'oc', 'name' => 'Occitan', 'native' => 'occitan, lenga d\'òc', ), 
      array( 'code' => 'oj', 'name' => 'Ojibwe, Oj', 'native' => 'ᐊᓂᔑᓈᐯᒧᐎᓐ', ), 
      array( 'code' => 'cu', 'name' => 'Old Church Slavonic, Church Slavonic, Old Bulgarian', 'native' => 'ѩзыкъ словѣньскъ', ), 
      array( 'code' => 'om', 'name' => 'Oromo', 'native' => 'Afaan Oromoo', ), 
      array( 'code' => 'or', 'name' => 'Oriya', 'native' => 'ଓଡ଼ିଆ', ), 
      array( 'code' => 'os', 'name' => 'Ossetian, Oss', 'native' => 'ирон æвзаг', ), 
      array( 'code' => 'pa', 'name' => 'Panjabi, Pun', 'native' => 'ਪੰਜਾਬੀ, پنجابی‎', ), 
      array( 'code' => 'pi', 'name' => 'Pāli', 'native' => 'पाऴि', ), 
      array( 'code' => 'fa', 'name' => 'Persian (Fa', 'native' => 'فارسی', ), 
      array( 'code' => 'pl', 'name' => 'Polish', 'native' => 'język polski, polszczyzna', ), 
      array( 'code' => 'ps', 'name' => 'Pashto, Pu', 'native' => 'پښتو', ), 
      array( 'code' => 'pt', 'name' => 'Portuguese', 'native' => 'português', ), 
      array( 'code' => 'qu', 'name' => 'Quechua', 'native' => 'Runa Simi, Kichwa', ), 
      array( 'code' => 'rm', 'name' => 'Romansh', 'native' => 'rumantsch grischun', ), 
      array( 'code' => 'rn', 'name' => 'Kirundi', 'native' => 'Ikirundi', ), 
      array( 'code' => 'ro', 'name' => 'Romanian', 'native' => 'limba română', ), 
      array( 'code' => 'ru', 'name' => 'Russian', 'native' => 'русский язык', ), 
      array( 'code' => 'sa', 'name' => 'Sanskrit (Saṁskṛta)', 'native' => 'संस्कृतम्', ), 
      array( 'code' => 'sc', 'name' => 'Sardinian', 'native' => 'sardu', ), 
      array( 'code' => 'sd', 'name' => 'Sindhi', 'native' => 'सिन्धी, سنڌي، سندھی‎', ), 
      array( 'code' => 'se', 'name' => 'Northern Sami', 'native' => 'Davvisámegiella', ), 
      array( 'code' => 'sm', 'name' => 'Samoan', 'native' => 'gagana fa\'a Samoa', ), 
      array( 'code' => 'sg', 'name' => 'Sango', 'native' => 'yângâ tî sängö', ), 
      array( 'code' => 'sr', 'name' => 'Serbian', 'native' => 'српски језик', ), 
      array( 'code' => 'gd', 'name' => 'Scottish Gaelic, Ga', 'native' => 'Gàidhlig', ), 
      array( 'code' => 'sn', 'name' => 'Shona', 'native' => 'chiShona', ), 
      array( 'code' => 'si', 'name' => 'Sinhala, Sinha', 'native' => 'සිංහල', ), 
      array( 'code' => 'sk', 'name' => 'Slovak', 'native' => 'slovenčina, slovenský jazyk', ), 
      array( 'code' => 'sl', 'name' => 'Slovene', 'native' => 'slovenski jezik, slovenščina', ), 
      array( 'code' => 'so', 'name' => 'Somali', 'native' => 'Soomaaliga, af Soomaali', ), 
      array( 'code' => 'st', 'name' => 'Southern Sotho', 'native' => 'Sesotho', ), 
      array( 'code' => 'es', 'name' => 'Spanish, Casti', 'native' => 'español, castellano', ), 
      array( 'code' => 'su', 'name' => 'Sundanese', 'native' => 'Basa Sunda', ), 
      array( 'code' => 'sw', 'name' => 'Swahili', 'native' => 'Kiswahili', ), 
      array( 'code' => 'ss', 'name' => 'Swati', 'native' => 'SiSwati', ), 
      array( 'code' => 'sv', 'name' => 'Swedish', 'native' => 'Svenska', ), 
      array( 'code' => 'ta', 'name' => 'Tamil', 'native' => 'தமிழ்', ), 
      array( 'code' => 'te', 'name' => 'Telugu', 'native' => 'తెలుగు', ), 
      array( 'code' => 'tg', 'name' => 'Tajik', 'native' => 'тоҷикӣ, toğikī, تاجیکی‎', ), 
      array( 'code' => 'th', 'name' => 'Thai', 'native' => 'ไทย', ), 
      array( 'code' => 'ti', 'name' => 'Tigrinya', 'native' => 'ትግርኛ', ), 
      array( 'code' => 'bo', 'name' => 'Tibetan Standard, Tibetan, Cen', 'native' => 'བོད་ཡིག', ), 
      array( 'code' => 'tk', 'name' => 'Turkmen', 'native' => 'Türkmen, Түркмен', ), 
      array( 'code' => 'tl', 'name' => 'Tagalog', 'native' => 'Wikang Tagalog, ᜏᜒᜃᜅ᜔ ᜆᜄᜎᜓᜄ᜔', ), 
      array( 'code' => 'tn', 'name' => 'Tswana', 'native' => 'Setswana', ), 
      array( 'code' => 'to', 'name' => 'Tonga (Tonga Isla', 'native' => 'faka Tonga', ), 
      array( 'code' => 'tr', 'name' => 'Turkish', 'native' => 'Türkçe', ), 
      array( 'code' => 'ts', 'name' => 'Tsonga', 'native' => 'Xitsonga', ), 
      array( 'code' => 'tt', 'name' => 'Tatar', 'native' => 'татар теле, tatar tele', ), 
      array( 'code' => 'tw', 'name' => 'Twi', 'native' => 'Twi', ), 
      array( 'code' => 'ty', 'name' => 'Tahitian', 'native' => 'Reo Tahiti', ), 
      array( 'code' => 'ug', 'name' => 'Uyghur, Ui', 'native' => 'Uyƣurqə, ئۇيغۇرچە‎', ), 
      array( 'code' => 'uk', 'name' => 'Ukrainian', 'native' => 'українська мова', ), 
      array( 'code' => 'ur', 'name' => 'Urdu', 'native' => 'اردو', ), 
      array( 'code' => 'uz', 'name' => 'Uzbek', 'native' => 'O‘zbek, Ўзбек, أۇزبېك‎', ), 
      array( 'code' => 've', 'name' => 'Venda', 'native' => 'Tshivenḓa', ), 
      array( 'code' => 'vi', 'name' => 'Vietnamese', 'native' => 'Tiếng Việt', ), 
      array( 'code' => 'vo', 'name' => 'Volapük', 'native' => 'Volapük', ), 
      array( 'code' => 'wa', 'name' => 'Walloon', 'native' => 'walon', ), 
      array( 'code' => 'cy', 'name' => 'Welsh', 'native' => 'Cymraeg', ), 
      array( 'code' => 'wo', 'name' => 'Wolof', 'native' => 'Wollof', ), 
      array( 'code' => 'fy', 'name' => 'Western Frisian', 'native' => 'Frysk', ), 
      array( 'code' => 'xh', 'name' => 'Xhosa', 'native' => 'isiXhosa', ), 
      array( 'code' => 'yi', 'name' => 'Yiddish', 'native' => 'ייִדיש', ), 
      array( 'code' => 'yo', 'name' => 'Yoruba', 'native' => 'Yorùbá', ), 
      array( 'code' => 'za', 'name' => 'Zhuang, Ch', 'native' => 'Saɯ cueŋƅ, Saw cuengh', ), 
      array( 'code' => 'zu', 'name' => 'Zulu', 'native' => 'isiZulu', ), 
    );

    foreach ($langs as $row) {
      $this->db->set('code', $row['code']);
      $this->db->set('name', $row['name']);
      $this->db->set('native', $row['native']);

      $this->db->insert('languages');
    }

    echo "table languages done.\n<br/>";
  }

  /**
   *
   */
  private function insurance_provider()
  {
    $provider = array(
      array('code' => '1', 'name' => 'Sonstige', ), 
      array('code' => '2', 'name' => 'AOK', ), 
      array('code' => '3', 'name' => 'DAK - Gesundheit', ), 
      array('code' => '4', 'name' => 'BARMER GEK', ), 
      array('code' => '5', 'name' => 'Techniker Krankenkasse', ), 
      array('code' => '6', 'name' => 'HEK - Hanseatische Krankenkasse', ), 
      array('code' => '7', 'name' => 'hkk', ), 
      array('code' => '8', 'name' => 'KKH - Kaufmännische Krankenkasse', ), 
      array('code' => '9', 'name' => 'BIG direkt gesund', ), 
      array('code' => '10', 'name' => 'IKK Brandenburg und Berlin', ), 
      array('code' => '11', 'name' => 'IKK classic', ), 
      array('code' => '12', 'name' => 'IKK gesund plus', ), 
      array('code' => '13', 'name' => 'IKK Nord', ), 
      array('code' => '14', 'name' => 'IKK Südwest', ), 
      array('code' => '15', 'name' => 'Vereinigte BKK', ), 
      array('code' => '16', 'name' => 'Continentale Betriebskrankenkasse', ), 
      array('code' => '17', 'name' => 'hkk Erste Gesundheit', ), 
      array('code' => '18', 'name' => 'Knappschaft', ), 
      array('code' => '19', 'name' => 'atlas BKK ahlmann', ), 
      array('code' => '20', 'name' => 'Audi BKK', ), 
      array('code' => '21', 'name' => 'BAHN-BKK', ), 
      array('code' => '22', 'name' => 'Bertelsmann BKK', ), 
      array('code' => '23', 'name' => 'BKK 24', ), 
      array('code' => '24', 'name' => 'BKK A.T.U', ), 
      array('code' => '25', 'name' => 'BKK Achenbach Buschhutten', ), 
      array('code' => '26', 'name' => 'BKK advita', ), 
      array('code' => '27', 'name' => 'BKK Aesculap', ), 
      array('code' => '28', 'name' => 'BKK Akzo Nobel', ), 
      array('code' => '29', 'name' => 'BKK B. Braun Melsungen AG', ), 
      array('code' => '30', 'name' => 'BKK Basell', ), 
      array('code' => '31', 'name' => 'BKK Beiersdorf AG', ), 
      array('code' => '32', 'name' => 'BKK BJB', ), 
      array('code' => '33', 'name' => 'BKK BPW Bergische Achsen KG', ), 
      array('code' => '34', 'name' => 'BKK Braun-Gillette', ), 
      array('code' => '35', 'name' => 'BKK DEMAG KRAUSS-MAFFEI', ), 
      array('code' => '36', 'name' => 'BKK der G. M. PFAFF AG', ), 
      array('code' => '37', 'name' => 'BKK der MTU Friedrichshafen', ), 
      array('code' => '38', 'name' => 'BKK der Thüringer Energieversorgung', ), 
      array('code' => '39', 'name' => 'BKK Deutsche Bank AG', ), 
      array('code' => '40', 'name' => 'BKK Diakonie', ), 
      array('code' => '41', 'name' => 'BKK ESSANELLE', ), 
      array('code' => '42', 'name' => 'BKK EUREGIO', ), 
      array('code' => '43', 'name' => 'BKK EWE', ), 
      array('code' => '44', 'name' => 'BKK exklusiv', ), 
      array('code' => '45', 'name' => 'BKK Faber-Castell &amp; Partner', ), 
      array('code' => '46', 'name' => 'BKK firmus', ), 
      array('code' => '47', 'name' => 'BKK Freudenberg', ), 
      array('code' => '48', 'name' => 'BKK Gildemeister Seidensticker ww', ), 
      array('code' => '49', 'name' => 'BKK GRILLO-WERKE AG', ), 
      array('code' => '50', 'name' => 'BKK Groz-Beckert', ), 
      array('code' => '51', 'name' => 'BKK HENSCHEL Plus', ), 
      array('code' => '52', 'name' => 'BKK Herford Minden Ravensberg', ), 
      array('code' => '53', 'name' => 'BKK Herkules', ), 
      array('code' => '54', 'name' => 'BKK IHV', ), 
      array('code' => '55', 'name' => 'BKK KARL MAYER', ), 
      array('code' => '56', 'name' => 'BKK Kassana', ), 
      array('code' => '57', 'name' => 'BKK KBA', ), 
      array('code' => '58', 'name' => 'BKK KEVAG KOBLENZ', ), 
      array('code' => '59', 'name' => 'BKK Krones', ), 
      array('code' => '60', 'name' => 'BKK Linde', ), 
      array('code' => '61', 'name' => 'BKK MAHLE', ), 
      array('code' => '62', 'name' => 'BKK MEDICUS', ), 
      array('code' => '63', 'name' => 'BKK Melitta Plus', ), 
      array('code' => '64', 'name' => 'BKK MEM', ), 
      array('code' => '65', 'name' => 'BKK MERCK', ), 
      array('code' => '66', 'name' => 'BKK Miele', ), 
      array('code' => '67', 'name' => 'BKK Mobil Oil', ), 
      array('code' => '68', 'name' => 'BKK Pfalz', ), 
      array('code' => '69', 'name' => 'BKK PHOENIX', ), 
      array('code' => '70', 'name' => 'BKK PricewaterhouseCoopers', ), 
      array('code' => '71', 'name' => 'BKK Publik', ), 
      array('code' => '72', 'name' => 'BKK Rieker.Ricosta.Weisser', ), 
      array('code' => '73', 'name' => 'BKK RWE', ), 
      array('code' => '74', 'name' => 'BKK Salzgitter', ), 
      array('code' => '75', 'name' => 'BKK Scheufelen', ), 
      array('code' => '76', 'name' => 'BKK Schleswig-Holstein', ), 
      array('code' => '77', 'name' => 'BKK Schwarzwald-Baar-Heuberg', ), 
      array('code' => '78', 'name' => 'BKK STADT AUGSBURG', ), 
      array('code' => '79', 'name' => 'BKK Technoform', ), 
      array('code' => '80', 'name' => 'BKK Textilgruppe Hof', ), 
      array('code' => '81', 'name' => 'BKK VDN', ), 
      array('code' => '82', 'name' => 'BKK VerbundPlus', ), 
      array('code' => '83', 'name' => 'BKK Verkehrsbau Union (VBU)', ), 
      array('code' => '84', 'name' => 'BKK VICTORIA - D.A.S.', ), 
      array('code' => '85', 'name' => 'BKK VITAL', ), 
      array('code' => '86', 'name' => 'BKK vor Ort', ), 
      array('code' => '87', 'name' => 'BKK Voralb', ), 
      array('code' => '88', 'name' => 'BKK Werra-Meissner', ), 
      array('code' => '89', 'name' => 'BKK Wirtschaft &amp; Finanzen', ), 
      array('code' => '90', 'name' => 'BKK Würth', ), 
      array('code' => '91', 'name' => 'BKK ZF &amp; Partner', ), 
      array('code' => '92', 'name' => 'BKK_DürkoppAdler', ), 
      array('code' => '93', 'name' => 'BMW BKK', ), 
      array('code' => '94', 'name' => 'Bosch BKK', ), 
      array('code' => '95', 'name' => 'Brandenburgische BKK', ), 
      array('code' => '96', 'name' => 'Daimler BKK', ), 
      array('code' => '97', 'name' => 'Debeka BKK', ), 
      array('code' => '98', 'name' => 'Deutsche BKK', ), 
      array('code' => '99', 'name' => 'DIE BERGISCHE KRANKENKASSE', ), 
      array('code' => '100', 'name' => 'Die Schwenninger Betriebskrankenkasse', ), 
      array('code' => '101', 'name' => 'E.ON BKK', ), 
      array('code' => '102', 'name' => 'energie-BKK', ), 
      array('code' => '103', 'name' => 'Ernst &amp; Young BKK', ), 
      array('code' => '104', 'name' => 'ESSO BKK', ), 
      array('code' => '105', 'name' => 'HEAG BKK', ), 
      array('code' => '106', 'name' => 'Heimat Krankenkasse', ), 
      array('code' => '107', 'name' => 'Metzinger BKK', ), 
      array('code' => '108', 'name' => 'mhplus Betriebskrankenkasse', ), 
      array('code' => '109', 'name' => 'Novitas BKK', ), 
      array('code' => '110', 'name' => 'pronova BKK', ), 
      array('code' => '111', 'name' => 'R+V BKK', ), 
      array('code' => '112', 'name' => 'Salus BKK', ), 
      array('code' => '113', 'name' => 'SECURVITA BKK', ), 
      array('code' => '114', 'name' => 'Shell BKK/LIFE', ), 
      array('code' => '115', 'name' => 'SIEMAG BKK', ), 
      array('code' => '116', 'name' => 'SBK', ), 
      array('code' => '117', 'name' => 'SKD BKK', ), 
      array('code' => '118', 'name' => 'Südzucker-BKK', ), 
      array('code' => '119', 'name' => 'TUI BKK', ), 
      array('code' => '120', 'name' => 'Vaillant BKK', ), 
      array('code' => '121', 'name' => 'Wieland BKK', ), 
      array('code' => '122', 'name' => 'WMF BKK', ), 
    );

    foreach ($provider as $row) {
      $this->db->set('code', $row['code']);
      $this->db->set('name', $row['name']);

      $this->db->insert('insurance_provider');
    }

    echo "table insurance_provider done.\n<br/>";
  }

}

/* End of file generate_tables.php */
/* Location: ./application/controllers/generate_tables.php */